### ISSUE TITLE
pretrained_classifier_model download

### ISSUE THREAD

**Issue by pribadihcr** [gallipoligiuseppe/TST-CycleGAN#1]
Hi @gallipoligiuseppe , where I can get the pretrained_classifier_model? Thanks

**Comment by gallipoligiuseppe** [comment]
Hi @pribadihcr, thank you for your interest in our work. You can find links to all the model checkpoints, including the pre-trained classifiers, in the corresponding section of the project README.

For your convenience, here are the links to the three classifiers, trained on each of the datasets considered: formality classifier (GYAFC - [family](https://huggingface.co/ggallipoli/formality_classifier_gyafc_family) and [music](https://huggingface.co/ggallipoli/formality_classifier_gyafc_music) domains) and sentiment classifier ([Yelp](https://huggingface.co/ggallipoli/sentiment_classifier_yelp)).
